name: After Release Work

on:
  workflow_run:
    workflows: ["Release Python Package"]
    types:
      - completed
  push:
    branches: ["main", "release"]
    tags: ["*"]

jobs:
  test:
    if: |
      github.event_name == 'workflow_run'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download version string from github action's artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: release.yaml
          name: release-version
      - name: check release version
        id: release-version
        run: |
          echo "::set-output name=VERSION::$(cat release-version.txt)"
          echo "::set-output name=VERSION_WO_V::$(cat release-version.txt | sed 's/v//')"
          echo "$(cat release-version.txt)"
      - name: print release version
        run: |
          echo ${{ steps.release-version.outputs.VERSION }}
          echo ${{ steps.release-version.outputs.VERSION_WO_V }}
