name: After Release Work

on:
  push:
    branches: ["main"]
    tags: ["*"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: check github variable
        run: |
          echo $GITHUB_REF
          echo ${{ github.event_name }}
          echo ${{ github.event.base_ref }}
