name: Release Python Package

on:
  release:
    types: [created]

jobs:
  release:
    if: |
      github.event_name == 'release'
    runs-on: ubuntu-latest
    env:
      VERSION_FILE: "pyverrt/__init__.py"
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Change package version
        run: |
          # from refs/tags/v1.2.3 get 1.2.3
          VERSION=$(echo $GITHUB_REF | sed 's#.*/v##')
          PLACEHOLDER='__version__ = "latest"'
          echo ${VERSION} ${VERSION_WITH_V} ${PLACEHOLDER} ${VERSION_FILE}
          grep "${PLACEHOLDER}" "${VERSION_FILE}"
          sed -i "s/${PLACEHOLDER}/__version__ = \"${VERSION}\"/g" "${VERSION_FILE}"
      - name: Extract version string
        run: |
          # from refs/tags/v1.2.3 get v1.2.3
          echo $GITHUB_REF | sed 's#.*/##' > release-version.txt
      - name: upload version string to github action's artifact.
        uses: actions/upload-artifact@v2
        with:
          name: release-version
          path: release-version.txt
      - name: Commit file
        run: |
          # from refs/tags/v1.2.3 get v1.2.3
          VERSION=$(cat release-version.txt)
          git config --local user.email "kbc8894@gmail.com"
          git config --local user.name "Byungchan Kim"
          git add ${VERSION_FILE}
          git commit -m "bumped version to ${VERSION}"
          git tag -f ${VERSION}
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: release
          tags: true
          force: true
